export const PROCESO_RESPONSABLES: Record<string, string[]> = {
  "Direccionamiento Estratégico": ["Eduard Forero", "Ricardo Arambulo", "William Romero"],
  "Gestión Comercial y de Mercadeo": ["Dayana Mejia"],
  "Administración de Nómina": ["William Romero"],
  "Administración de Personal": ["Jennifer Cervantes"],
  "Selección de Personal": ["Patricia Jimenez"],
  "Gestión de Servicio al Cliente": ["Ricardo Arambulo", "Dayana Mejia"],
  "Gestión Administrativa y Financiera": ["Yuly Peña"],
  "Gestión de Talento Humano": ["Patricia Jimenez"],
  "Employer of Record": ["German Hincapie"],
  "Employer of Record Sucursales": ["Tatiana Chavarro"],
  "Gestión Integral": ["Ingrid Pineda"],
  "Outsourcing de tesorería": ["Alfonso Fonseca"],
};

export const RESPONSABLES_SEGUIMIENTO: string[] = [
  "Eduard Forero",
  "Alejandro Echavarria",
  "Alfonso Fonseca",
  "Yenny Delgado",
  "Tatiana Cumbe",
  "Viviana Guzman",
  "Rocio Guacaneme",
  "Giovanna Guio",
  "Alba Luz Borja",
  "German Hincapie",
  "Deissy Preciado",
  "Kevin Gonzalez",
  "Lina Chinome",
  "Fabian Morales",
  "Marco Castiblanco",
  "Yadira Pineda",
  "Patricia Osorio",
  "Ricardo Arambulo Polo",
  "Patricia Jimenez",
  "Jennifer Cervantes",
  "Yina Vega",
  "William Romero",
  "Diana Hernandez",
  "Michael Pertuz",
  "Julieth Bonilla",
  "Alba Suarez",
  "Nathalie Vaquiro",
  "Yuly Peña",
  "Selección S&P",
  "Lorena Garcia Navarro",
  "Tatiana Chavarro",
  "Viviana Martinez",
  "Paola Velasquez",
  "Dayan Manjarres",
  "Carolina Morales",
  "Brayan Pardo",
  "Camila Herrera",
  "Paola Gonzalez",
  "Ana Maria Gutierrez",
  "Ingrid Pineda",
  "Erika Letrado",
  "Jhon Jairo Leon",
  "Stiven Narváez",
  "Yeferson Pineda",
  "Nicolas Ballesteros",
  "Sandra Bello",
  "Sharon Amaya",
  "Lina Guio",
  "Cristian Parada",
  "Diana Mendez",
  "Simon Tschannen",
  "Eduardo Castañeda",
  "Jose Sergio Veintemilla",
  "Juan David Urbina",
  "Dayana Mejia",
];

// Mapeo completo de responsables → correo electrónico.
// Incluye a todos los miembros de RESPONSABLES_SEGUIMIENTO.
// Deja en "" los correos que aún no estén configurados — esa persona no recibirá correos hasta que se añada su email.
export const RESPONSABLE_EMAILS: Record<string, string> = {
  // ── Correos configurados ─────────────────────────────────────────────────
  "Ricardo Arambulo":      "cristianparada531@gmail.com",
  "Ricardo Arambulo Polo": "cristianparada531@gmail.com",
  "William Romero":        "automatizacion2@solutionsandpayroll.com",
  // ── Pendientes de configurar ─────────────────────────────────────────────
  "Alba Luz Borja":          "",
  "Alba Suarez":             "",
  "Alejandro Echavarria":    "",
  "Alfonso Fonseca":         "",
  "Ana Maria Gutierrez":     "",
  "Brayan Pardo":            "",
  "Camila Herrera":          "",
  "Carolina Morales":        "",
  "Cristian Parada":         "",
  "Dayana Mejia":            "",
  "Dayan Manjarres":         "",
  "Deissy Preciado":         "",
  "Diana Hernandez":         "",
  "Diana Mendez":            "",
  "Eduard Forero":           "",
  "Eduardo Castañeda":       "",
  "Erika Letrado":           "",
  "Fabian Morales":          "",
  "German Hincapie":         "",
  "Giovanna Guio":           "",
  "Ingrid Pineda":           "",
  "Jennifer Cervantes":      "",
  "Jhon Jairo Leon":         "",
  "Jose Sergio Veintemilla": "",
  "Juan David Urbina":       "",
  "Julieth Bonilla":         "",
  "Kevin Gonzalez":          "",
  "Lina Chinome":            "",
  "Lina Guio":               "",
  "Lorena Garcia Navarro":   "",
  "Marco Castiblanco":       "",
  "Michael Pertuz":          "",
  "Nathalie Vaquiro":        "",
  "Nicolas Ballesteros":     "",
  "Paola Gonzalez":          "",
  "Paola Velasquez":         "",
  "Patricia Jimenez":        "",
  "Patricia Osorio":         "",
  "Rocio Guacaneme":         "",
  "Sandra Bello":            "",
  "Selección S&P":           "",
  "Sharon Amaya":            "",
  "Simon Tschannen":         "",
  "Stiven Narváez":          "",
  "Tatiana Chavarro":        "",
  "Tatiana Cumbe":           "",
  "Viviana Guzman":          "",
  "Viviana Martinez":        "",
  "Yadira Pineda":           "",
  "Yeferson Pineda":         "",
  "Yenny Delgado":           "",
  "Yina Vega":               "",
  "Yuly Peña":               "",
};

const normalize = (value: string) => value.trim().toLowerCase();

export const getResponsablesByProceso = (proceso: string): string[] => {
  return PROCESO_RESPONSABLES[proceso] ?? [];
};

export const getResponsableEmailsByProceso = (proceso: string): string[] => {
  const responsables = getResponsablesByProceso(proceso);
  const emails = responsables
    .map((nombre) => RESPONSABLE_EMAILS[nombre])
    .map((email) => email?.trim())
    .filter((email): email is string => Boolean(email));

  return [...new Set(emails.map(normalize))];
};
